
services:
  node-red:
    build: ./docker-files/node-red
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
  influxdb:
    build: ./docker-files/influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
  grafana:
    build: ./docker-files/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  node-red-data:
    driver: local
    driver_opts:
      type: none
      device: ./docker-volumes/node-red-data
      o: bind
  influxdb-data:
    driver: local
    driver_opts:
      type: none
      device: ./docker-volumes/influxdb-data
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: ./docker-volumes/grafana-data
      o: bind


networks:
  node-red-net: